"""
Excel export for COREP C 01.00 template results.

Generates a formatted .xlsx workbook with three sheets:
  1. C 01.00 Own Funds — populated template
  2. Audit Trail        — reasoning + citations per field
  3. Validation Results  — pass/fail for each rule
"""

from __future__ import annotations

import io
from typing import Optional

from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

from models import PopulatedField, ValidationResult

# ---------------------------------------------------------------------------
# Style constants
# ---------------------------------------------------------------------------

_HEADER_FILL = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
_HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
_TITLE_FONT = Font(bold=True, size=14, color="1F4E79")
_SUBTITLE_FONT = Font(bold=True, size=10, color="555555")
_THIN_BORDER = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)

_CONFIDENCE_FILLS = {
    "high": PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid"),
    "medium": PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid"),
    "low": PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid"),
}

_PASS_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
_FAIL_FILL = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")


def _style_header_row(ws, row: int, cols: int):
    for col in range(1, cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = _THIN_BORDER


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------

def _build_template_sheet(wb: Workbook, fields: list[PopulatedField]):
    ws = wb.active
    ws.title = "C 01.00 Own Funds"

    # Title
    ws.merge_cells("A1:D1")
    ws["A1"] = "COREP Template C 01.00 — Own Funds"
    ws["A1"].font = _TITLE_FONT

    ws.merge_cells("A2:D2")
    ws["A2"] = "Values in thousands GBP | Generated by COREP Assistant"
    ws["A2"].font = _SUBTITLE_FONT

    # Headers
    headers = ["Field ID", "Field Name", "Value (£000s)", "Confidence"]
    for col, h in enumerate(headers, 1):
        ws.cell(row=4, column=col, value=h)
    _style_header_row(ws, 4, len(headers))

    # Data rows
    for i, field in enumerate(fields, 5):
        ws.cell(row=i, column=1, value=field.field_id).border = _THIN_BORDER
        ws.cell(row=i, column=2, value=field.field_name).border = _THIN_BORDER

        val_cell = ws.cell(row=i, column=3, value=field.value)
        val_cell.number_format = "#,##0"
        val_cell.border = _THIN_BORDER
        val_cell.alignment = Alignment(horizontal="right")

        conf_cell = ws.cell(row=i, column=4, value=field.confidence)
        conf_cell.fill = _CONFIDENCE_FILLS.get(field.confidence, PatternFill())
        conf_cell.border = _THIN_BORDER
        conf_cell.alignment = Alignment(horizontal="center")

        # Add reasoning as a comment on the value cell
        comment_text = (
            f"Reasoning: {field.reasoning}\n\n"
            f"Citations: {', '.join(field.citations)}"
        )
        val_cell.comment = Comment(comment_text, "COREP Assistant")

    # Column widths
    ws.column_dimensions["A"].width = 16
    ws.column_dimensions["B"].width = 55
    ws.column_dimensions["C"].width = 18
    ws.column_dimensions["D"].width = 14


def _build_audit_sheet(wb: Workbook, fields: list[PopulatedField]):
    ws = wb.create_sheet("Audit Trail")

    ws.merge_cells("A1:E1")
    ws["A1"] = "Audit Trail — Field-by-Field Reasoning"
    ws["A1"].font = _TITLE_FONT

    headers = ["Field ID", "Field Name", "Value (£000s)", "Reasoning", "Citations"]
    for col, h in enumerate(headers, 1):
        ws.cell(row=3, column=col, value=h)
    _style_header_row(ws, 3, len(headers))

    for i, field in enumerate(fields, 4):
        ws.cell(row=i, column=1, value=field.field_id).border = _THIN_BORDER
        ws.cell(row=i, column=2, value=field.field_name).border = _THIN_BORDER

        val_cell = ws.cell(row=i, column=3, value=field.value)
        val_cell.number_format = "#,##0"
        val_cell.border = _THIN_BORDER

        reason_cell = ws.cell(row=i, column=4, value=field.reasoning)
        reason_cell.alignment = Alignment(wrap_text=True, vertical="top")
        reason_cell.border = _THIN_BORDER

        cite_cell = ws.cell(row=i, column=5, value=", ".join(field.citations))
        cite_cell.alignment = Alignment(wrap_text=True, vertical="top")
        cite_cell.border = _THIN_BORDER

    ws.column_dimensions["A"].width = 16
    ws.column_dimensions["B"].width = 45
    ws.column_dimensions["C"].width = 16
    ws.column_dimensions["D"].width = 60
    ws.column_dimensions["E"].width = 35


def _build_validation_sheet(wb: Workbook, results: list[ValidationResult]):
    ws = wb.create_sheet("Validation Results")

    ws.merge_cells("A1:E1")
    ws["A1"] = "Validation Results — Intra-Template Checks"
    ws["A1"].font = _TITLE_FONT

    headers = ["Rule ID", "Description", "Status", "Expected", "Actual"]
    for col, h in enumerate(headers, 1):
        ws.cell(row=3, column=col, value=h)
    _style_header_row(ws, 3, len(headers))

    for i, r in enumerate(results, 4):
        ws.cell(row=i, column=1, value=r.rule_id).border = _THIN_BORDER
        ws.cell(row=i, column=2, value=r.description).border = _THIN_BORDER

        status_cell = ws.cell(row=i, column=3, value="PASS" if r.passed else "FAIL")
        status_cell.fill = _PASS_FILL if r.passed else _FAIL_FILL
        status_cell.font = Font(bold=True)
        status_cell.alignment = Alignment(horizontal="center")
        status_cell.border = _THIN_BORDER

        exp_cell = ws.cell(row=i, column=4, value=r.expected if r.expected is not None else "")
        exp_cell.number_format = "#,##0"
        exp_cell.border = _THIN_BORDER

        act_cell = ws.cell(row=i, column=5, value=r.actual if r.actual is not None else "")
        act_cell.number_format = "#,##0"
        act_cell.border = _THIN_BORDER

    ws.column_dimensions["A"].width = 12
    ws.column_dimensions["B"].width = 55
    ws.column_dimensions["C"].width = 12
    ws.column_dimensions["D"].width = 16
    ws.column_dimensions["E"].width = 16


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_excel(
    fields: list[PopulatedField],
    validation_results: list[ValidationResult],
    session_id: str = "export",
) -> io.BytesIO:
    """
    Generate a complete COREP C 01.00 Excel workbook.

    Returns a BytesIO buffer ready for Streamlit's download_button.
    """
    wb = Workbook()

    _build_template_sheet(wb, fields)
    _build_audit_sheet(wb, fields)
    _build_validation_sheet(wb, validation_results)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
